### ISSUE TITLE
Create Empty State Template 

### ISSUE THREAD

**Issue by benni345** [adjust-design-system/design-tokens#36]
**Problem:**
Empty states are a pattern that are commonly used. This should be designed and added to the core library 

Design a template for the empty state 
Consider:
Header text
Body text
Action Buttons 

**Tasks:**

- [ ] Research common empty state patterns
- [ ] Create empty state template design 
- [ ] Spec Empty state template design 

**Acceptance Criteria:**
Empty state template added to patterns

**Resources:**
A right up I did on empty states in my last project, there might be some things that are interesting in there https://www.behance.net/gallery/84809305/UX-Case-Study-Onboarding-Empty-States
