### ISSUE TITLE
Create the Chip component

### ISSUE THREAD

**Issue by benni345** [adjust-design-system/design-tokens#45]
**Problem:**
We have a new chip component that will be used in filters. the design has not been finalised for this 

we have a filter chip component - name to chips and improve the design 

**Tasks:**

- [ ] Come up with a design for the chip component
- [ ] cover states and behaviors
- [x] rename FilterChip to Chip 
- [x] Add to symbols and the index page 

**Acceptance Criteria:** 
Chip component added to symbols and index page

**Comment by reimar** [comment]
This ticket will become obsolete in context of the whole Filter Input exploration from Joachim. Will close it for now.
