### ISSUE TITLE
Remove tabs variations

### ISSUE THREAD

**Issue by reimar** [adjust-design-system/design-tokens#55]
**Problem:**
We will most likely never use the _large_ and _above_ tab variations, keeping them in the library might just be confusing.

**Tasks:**

- [x] Remove the large tabs
- [x] Remove the _above_ tabs variant
- [x] Make the _below_ variant the default

**Acceptance Criteria**:
Tabs are only avail. in small and medium, no other variants.
